import { Walkthrough } from './Walkthrough.jsx';
import { useState, useRef } from 'react';
import { ArrowRight, ArrowUpRight, Check, Copy, GithubLogo, List, X, ChatCircleText, Code, GitPullRequest, Stack } from '@phosphor-icons/react';
import syncEngine from './assets/sync-engine.png';
import { INSTALL, REPO, TOOL_LIST, VERSION, readme, repoFile } from './repo.js';
const workflows=[
{name:'Plan',command:'/define',description:'Turn an idea into a clear plan. Move from an interview to a spec, test cases, and an implementation plan before writing code.',example:'Help me plan a todo app with sign-in, a database, and tests before we start building.',comments:['Clarify the goal and write a spec','Define test cases and an ordered implementation plan','Start building with shared context'],link:readme('planning-pipeline-define-before-you-build')},
{name:'Build',command:'/parallel-build',description:'Build with the right specialists. CraftKit detects your platform and selects the agents that matter for the work at hand.',example:'Add sign-in to my app. Have the relevant specialists review the changes and check that it works.',comments:['Detect the platform and classify the task','Select relevant specialists for the change','Build, review, and verify the result'],link:readme('dynamic-workflows-default')},
{name:'Review',command:'/parallel-review',description:'Get a focused review of your actual changes. Platform specialists check the diff while an adversarial reviewer challenges the result.',example:'Review my changes for bugs, accessibility issues, and anything that could be simpler.',comments:['Collect and classify the actual changes','Run relevant reviewers in parallel','Bring findings together for the next step'],link:readme('dynamic-workflows-default')},
{name:'Ship',command:'/parallel-ship',description:'Take a change through a shared shipping workflow. Bring review and verification together before preparing it to ship.',example:'Help me get this change ready to ship. Review it, run the checks, and summarize anything I need to address.',comments:['Review the change with selected specialists','Run the verification your project needs','Prepare a clear, reviewable result'],link:readme('dynamic-workflows-default')}];
function CopyCommand({text=INSTALL,label='Copy install command',block=false}){
const [status,setStatus]=useState(''); const codeRef=useRef(null);
async function copy(){let copied=false;try{if(navigator.clipboard){await navigator.clipboard.writeText(text);copied=true}}catch{}if(!copied){const field=document.createElement('textarea');field.value=text;field.setAttribute('readonly','');field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();copied=document.execCommand('copy');field.remove()}if(copied)setStatus('Copied!');else{const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(codeRef.current);selection.removeAllRanges();selection.addRange(range);setStatus('Selected: press Ctrl/Cmd+C')}window.setTimeout(()=>setStatus(''),3500)}
return <div className={`copy-wrap ${block?'copy-block':''}`}><div className="command"><span className="prompt" aria-hidden="true">$</span><code ref={codeRef}>{text}</code><button type="button" aria-label={label} title={label} onClick={copy}>{status==='Copied!'?<Check size={19}/>:<Copy size={19}/>}</button></div><span className="copy-status" role="status">{status}</span></div>}
function Wordmark(){return <span className="brand-lockup"><span className="wordmark">Craft<span>Kit</span></span><span className="brand-tagline">AI-gnostic</span></span>}
export function App(){const [active,setActive]=useState(0),[menuOpen,setMenuOpen]=useState(false),[method,setMethod]=useState('npm');const workflow=workflows[active];
function changeTab(e){let next=active;if(e.key==='ArrowRight')next=(active+1)%4;else if(e.key==='ArrowLeft')next=(active+3)%4;else if(e.key==='Home')next=0;else if(e.key==='End')next=3;else return;e.preventDefault();setActive(next);document.getElementById(`tab-${next}`).focus()}
return <><a className="skip-link" href="#main">Skip to content</a><header className="header"><div className="container header-inner"><a href="#" aria-label="CraftKit home"><Wordmark/></a><nav aria-label="Main navigation" className={menuOpen?'nav open':'nav'}><a href="#example" onClick={()=>setMenuOpen(false)}>How it works</a><a href="#workflows" onClick={()=>setMenuOpen(false)}>Workflows</a><a href="#install" onClick={()=>setMenuOpen(false)}>Install</a><a href={REPO} target="_blank" rel="noreferrer">GitHub</a></nav><a className="github-icon" href={REPO} aria-label="CraftKit on GitHub (opens in new tab)" target="_blank" rel="noreferrer"><GithubLogo size={29} weight="fill"/></a><button className="menu-toggle" aria-expanded={menuOpen} aria-label={menuOpen?'Close navigation':'Open navigation'} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X size={24}/>:<List size={24}/>}</button></div></header>
<main id="main"><section className="hero" aria-labelledby="hero-heading"><div className="container hero-copy"><span className="eyebrow badge">ONE REPO. EVERY AI TOOL.</span><h1 id="hero-heading">Pull once.<br/><span>Power every tool.</span></h1><p className="hero-description">Your AI coding skills, rules, and workflows, in sync across your entire stack.</p><div className="hero-actions"><a className="button primary" href="#install">Get started <ArrowRight size={20}/></a><a className="button secondary" href={REPO} target="_blank" rel="noreferrer"><GithubLogo size={23} weight="fill"/> View on GitHub</a></div><CopyCommand/></div><figure className="container sync-figure" id="how-it-works"><img src={syncEngine} alt={`CraftKit syncs one repository of skills, rules, commands, and agents across ${TOOL_LIST}.`} width="1200" height="300" fetchPriority="high"/><figcaption className="mobile-tools">One shared toolkit for <strong>{TOOL_LIST}.</strong></figcaption></figure></section>
<section className="workflow-section" id="workflows" aria-labelledby="workflow-heading"><div className="container"><span className="eyebrow">FROM IDEA TO SHIP</span><h2 id="workflow-heading">A shared workflow, from idea to ship.</h2><div className="tabs" role="tablist" aria-label="Coding workflow">{workflows.map((item,i)=><button key={item.name} id={`tab-${i}`} type="button" role="tab" aria-selected={active===i} aria-controls="workflow-panel" tabIndex={active===i?0:-1} onKeyDown={changeTab} onClick={()=>setActive(i)}>{item.name}</button>)}</div><div className="workflow-panel" role="tabpanel" id="workflow-panel" aria-labelledby={`tab-${active}`} tabIndex={0}><div className="workflow-detail"><span className="eyebrow">STEP {active+1}</span><h3>{workflow.command}</h3><p>{workflow.description}</p><a className="text-link" href={workflow.link} target="_blank" rel="noreferrer">Explore the workflow <ArrowUpRight size={17}/></a></div><div className="terminal"><div className="terminal-title"><ChatCircleText size={17}/> Example request</div><p className="natural-request">“{workflow.example}”</p><div className="terminal-comments">{workflow.comments.map(line=><div key={line}><Check size={15} aria-hidden="true"/>{line}</div>)}</div></div></div></div></section>
<Walkthrough/>
<section className="toolkit-section container" aria-labelledby="toolkit-heading"><div className="section-intro"><span className="eyebrow">YOUR PLAYBOOK, EVERYWHERE</span><h2 id="toolkit-heading">Switch tools.<br/>Keep your standards.</h2><p>Keep the source in one place. Let CraftKit handle the tool-specific formats.</p></div><div className="benefit-list"><article><Stack size={24}/><div><h3>One source of truth</h3><p>Manage skills, rules, commands, and agents in a single repository. Update the source, then sync it across your tools.</p></div></article><article><Code size={24}/><div><h3>Built for your platform</h3><p>Workflows detect web, React Native, Android, and iOS projects and route work to the relevant specialists.</p></div></article><article><GitPullRequest size={24}/><div><h3>Stay in sync as you work</h3><p>Git installs use post-merge and post-rewrite hooks. Pull an update to add, refresh, or remove installed skills.</p></div></article></div></section>
<section className="install-section" id="install" aria-labelledby="install-heading"><div className="container install-inner"><div><span className="eyebrow">MAKE IT YOUR TOOLKIT</span><h2 id="install-heading">One install.<br/>A shared way to build.</h2><p>Bring CraftKit to the AI tools you already use.</p><a className="text-link" href={readme('install')} target="_blank" rel="noreferrer">Read the installation guide <ArrowUpRight size={17}/></a></div><div className="install-options"><div className="method-switch" role="group" aria-label="Installation method"><button type="button" aria-pressed={method==='npm'} onClick={()=>setMethod('npm')}>npm</button><button type="button" aria-pressed={method==='git'} onClick={()=>setMethod('git')}>Git</button></div><h3>{method==='npm'?'Install with npm':'Install from GitHub'}</h3><p>{method==='npm'?'Install globally, with version pinning and rollback.':'Clone once. Future pulls automatically sync your tools.'}</p><CopyCommand block text={method==='npm'?INSTALL:`git clone ${REPO}.git ~/craftkit\ncd ~/craftkit\nbash install.sh`} label={`Copy ${method} installation commands`}/><p className="requirements">Requires bash 3.2+ and curl{method==='npm'?', plus npm':', plus Git'}. In Codex, review and trust the hooks with <code>/hooks</code> after installation.</p></div></div></section></main>
<footer className="container footer"><a href="#" aria-label="Back to top"><Wordmark/></a><p>One repo. A shared craft. <a href={`${REPO}/releases/tag/v${VERSION}`} target="_blank" rel="noreferrer">v{VERSION}</a></p><div><a href={REPO} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a><a href={repoFile('LICENSE')} target="_blank" rel="noreferrer">License</a><a href={repoFile('CONTRIBUTING.md')} target="_blank" rel="noreferrer">Contribute</a></div></footer></>}
